---
title: "chem313_AAanalysis"
author: "Emily McLaughlin Sta. Maria"
date: "11/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)

##don't forget to import tidy_AA.csv

```

```{r}

mean(ICPMS_tidy_example$rsd, na.rm=TRUE) 
mean(tidy_AA$percent_rsd, na.rm=TRUE)

```

```{r}

#trying out that calibration curve

cal <- tidy_AA %>%
    filter(type == "CalStd" | type == "CalStd2" | type == "CalStd4") %>%
    select(concentration, mean_abs)
View(cal)

model <- lm(cal$mean_abs ~ cal$concentration)

plot(cal$mean_abs ~ cal$concentration,
     xlab = "Concentrations of Cr (ppm)",
     
     #oh boy is this ppm. It is.
     
     ylab = "Mean Absorbance") +
  abline(model, col = "red") +
  title("Calibration for Cr")

summary(model)
## abs = [(0.0130+/-0.0004)1/ppb] * [Cr in ppb] - 0.002+/-0.002
##mean = 0.0130130
##intercept = -0.0019470

slope <- 0.0130130
intercept <- -0.0019470
slope_error <- 0.0004232
intercept_error <- 0.0021581

Cal_Curve_Eq <- data.frame(slope, intercept, slope_error, intercept_error)
Cal_Curve_Eq
```

```{r}

##method blank

##MB in site is the blanks

##in function(*here) type on input
FixBlank <- function(Site){
  A <- tidy_AA%>%
  filter(site == Site) 
  #first site is column name, second Site is from function(Site)
  Cal_blank <- Cal_Curve_Eq
  m_blank <- Cal_Curve_Eq$slope
  b_blank <- Cal_Curve_Eq$intercept
  y_blank <- A$mean_abs
  x_blank <- (y_blank-b_blank)/m_blank #x_blank = uncorrect conc
  corrected_blank <- x_blank*(A$total_volume/1000)
  average <- mean(corrected_blank)
  sd(corrected_blank)
  blank_95CI <- qt(0.95, df=length(corrected_blank)-1)*sd(corrected_blank)/(sqrt(length(corrected_blank))) ##95% CI's... copy and paste when needed!
  blank_data <- data.frame(site=Site, average, sd(corrected_blank), blank_95CI)
}

AA_MB <- FixBlank("MB")
#AA_QC <- FixBlank("QC") I think this should actually have the soil and blank corrections? So I'm adding to next chunk

  ##different with sites, need to account for mass of soil

```

```{r}

##ppb 

AA_samples <- function(Site){
  A <- tidy_AA%>%
  filter(site == Site) 
  #first site is column name, second Site is from function(Site)
  Cal_blank <- Cal_Curve_Eq
  m_conc <- Cal_Curve_Eq$slope
  b_conc <- Cal_Curve_Eq$intercept
  y_conc <- A$mean_abs
  x_conc <- (y_conc-b_conc)/(m_conc) 
  corrected_conc <- x_conc*(A$total_volume/1000)/((A$mass_of_soil/1000))
  maybe <- corrected_conc - AA_MB$average ##this is just the concentrations - blank = final real life concentration I guess theoretically
  mean(maybe)
  sd(maybe)
  CI <- qt(0.95, df=length(maybe)-1)*sd(maybe)/(sqrt(length(maybe))) ##95% CI's... copy and paste when needed!
 Conc_data <- data.frame(site=Site, mean(maybe), sd(maybe), CI)
}


AA_A <- AA_samples_ppb("A")
AA_B <- AA_samples_ppb("B")
AA_C <- AA_samples_ppb("C")
AA_D <- AA_samples_ppb("D")
AA_E <- AA_samples_ppb("E")
AA_F <- AA_samples_ppb("F")
AA_QC <- AA_samples_ppb("QC")

AA_A
AA_B
AA_C
AA_D
AA_E
AA_F
AA_QC
##units are ppm 



```

```{r}

AA_samples <- function(Site){
  A <- tidy_AA%>%
  filter(site == Site) 
  #first site is column name, second Site is from function(Site)
  Cal_blank <- Cal_Curve_Eq
  m_conc <- Cal_Curve_Eq$slope
  b_conc <- Cal_Curve_Eq$intercept
  y_conc <- A$mean_abs
  x_conc <- (y_conc-b_conc)/(m_conc) 
  corrected_conc <- x_conc*(A$total_volume/1000)/((A$mass_of_soil/1000))
  maybe <- corrected_conc - AA_MB$average ##this is just the concentrations - blank = final real life concentration I guess theoretically
  mean(maybe)
  sd(maybe)
  CI <- qt(0.95, df=length(maybe)-1)*sd(maybe)/(sqrt(length(maybe))) ##95% CI's... copy and paste when needed!
 Conc_data <- data.frame(site=Site, mean(maybe), sd(maybe), CI)
}

```








```{r}

##So I'm bringing sample_data from ICPMSAnalysis.Rmd into this one, so I can compare them, if I need t-tests or whatnot 

##so upload chem313_ICPMSAnalysis.csv

##Rn imma try to double filter but idk how haha

Average_byMetalSite <- function(Site, Metal){
  C <- ICPMS_data%>%
  filter(site == Site, metal == Metal) 
  #first site is column name, second Site is from function(Site)
  MEAN <- mean(C$conc_blanked/1000) ##dividing by 1000 to convert from ppb to ppm, to match AA data
  SD <- sd(C$conc_blanked/1000)
  CI <- qt(0.95, df=length(C$conc_blanked/1000)-1)*SD/(sqrt(length(C$conc_blanked/1000))) ##95% CI's... copy and paste when needed!
 Conc_data <- data.frame(site = Site, metal = Metal, MEAN, SD, CI)
}

ICPMS_A_As75 <- Average_byMetalSite("A", "As75")
ICPMS_A_Cd111 <- Average_byMetalSite("A", "Cd111")
ICPMS_A_Cd114 <- Average_byMetalSite("A", "Cd114")
ICPMS_A_Cr52 <- Average_byMetalSite("A", "Cr52")
ICPMS_A_Cr53 <- Average_byMetalSite("A", "Cr53")
ICPMS_A_Pb208 <- Average_byMetalSite("A", "Pb208")

ICPMS_B_As75 <- Average_byMetalSite("B", "As75")
ICPMS_B_Cd111 <- Average_byMetalSite("B", "Cd111")
ICPMS_B_Cd114 <- Average_byMetalSite("B", "Cd114")
ICPMS_B_Cr52 <- Average_byMetalSite("B", "Cr52")
ICPMS_B_Cr53 <- Average_byMetalSite("B", "Cr53")
ICPMS_B_Pb208 <- Average_byMetalSite("B", "Pb208")

ICPMS_C_As75 <- Average_byMetalSite("C", "As75")
ICPMS_C_Cd111 <- Average_byMetalSite("C", "Cd111")
ICPMS_C_Cd114 <- Average_byMetalSite("C", "Cd114")
ICPMS_C_Cr52 <- Average_byMetalSite("C", "Cr52")
ICPMS_C_Cr53 <- Average_byMetalSite("C", "Cr53")
ICPMS_C_Pb208 <- Average_byMetalSite("C", "Pb208")

ICPMS_D_As75 <- Average_byMetalSite("D", "As75")
ICPMS_D_Cd111 <- Average_byMetalSite("D", "Cd111")
ICPMS_D_Cd114 <- Average_byMetalSite("D", "Cd114")
ICPMS_D_Cr52 <- Average_byMetalSite("D", "Cr52")
ICPMS_D_Cr53 <- Average_byMetalSite("D", "Cr53")
ICPMS_D_Pb208 <- Average_byMetalSite("D", "Pb208")

ICPMS_E_As75 <- Average_byMetalSite("E", "As75")
ICPMS_E_Cd111 <- Average_byMetalSite("E", "Cd111")
ICPMS_E_Cd114 <- Average_byMetalSite("E", "Cd114")
ICPMS_E_Cr52 <- Average_byMetalSite("E", "Cr52")
ICPMS_E_Cr53 <- Average_byMetalSite("E", "Cr53")
ICPMS_E_Pb208 <- Average_byMetalSite("E", "Pb208")

ICPMS_F_As75 <- Average_byMetalSite("F", "As75")
ICPMS_F_Cd111 <- Average_byMetalSite("F", "Cd111")
ICPMS_F_Cd114 <- Average_byMetalSite("F", "Cd114")
ICPMS_F_Cr52 <- Average_byMetalSite("F", "Cr52")
ICPMS_F_Cr53 <- Average_byMetalSite("F", "Cr53")
ICPMS_F_Pb208 <- Average_byMetalSite("F", "Pb208")

ICPMS_QC_As75 <- Average_byMetalSite("QC", "As75")
ICPMS_QC_Cd111 <- Average_byMetalSite("QC", "Cd111")
ICPMS_QC_Cd114 <- Average_byMetalSite("QC", "Cd114")
ICPMS_QC_Cr52 <- Average_byMetalSite("QC", "Cr52")
ICPMS_QC_Cr53 <- Average_byMetalSite("QC", "Cr53")
ICPMS_QC_Pb208 <- Average_byMetalSite("QC", "Pb208")

ICPMS_QC_As75
ICPMS_QC_Cd111
ICPMS_QC_Cd114
ICPMS_QC_Cr52
ICPMS_QC_Cr53
ICPMS_QC_Pb208

ICPMS_A_As75
ICPMS_B_As75
ICPMS_C_As75
ICPMS_D_As75
ICPMS_E_As75
ICPMS_F_As75

ICPMS_A_Cd111
ICPMS_B_Cd111
ICPMS_C_Cd111
ICPMS_D_Cd111
ICPMS_E_Cd111
ICPMS_F_Cd111

ICPMS_A_Cd114
ICPMS_B_Cd114
ICPMS_C_Cd114
ICPMS_D_Cd114
ICPMS_E_Cd114
ICPMS_F_Cd114

ICPMS_A_Cr52
ICPMS_B_Cr52
ICPMS_C_Cr52
ICPMS_D_Cr52
ICPMS_E_Cr52
ICPMS_F_Cr52

ICPMS_A_Cr53
ICPMS_B_Cr53
ICPMS_C_Cr53
ICPMS_D_Cr53
ICPMS_E_Cr53
ICPMS_F_Cr53

ICPMS_A_Pb208
ICPMS_B_Pb208
ICPMS_C_Pb208
ICPMS_D_Pb208
ICPMS_E_Pb208
ICPMS_F_Pb208



##These values are now in ppm, like AA data

```

```{r}

##average of each metal

As <- c(2.867858, 3.093917, 3.774724, 2.36024, 4.119131, 3.539387)
Cd__111 <- c(0.1171607, 0.1376244, 0.1663066, 0.1383805, 0.1135686, 0.0843112)
Cd__114 <- c(0.2490245, 0.2786682, 0.2978427, 0.2030614, 0.1401641, 0.09983913)
Pb <- c(402.3014, 356.0249, 281.8168, 197.4917, 120.7364, 99.13809)
ICr52 <- c(23.73373, 16.91288, 34.00937, 12.96789, 19.49183, 11.5554)
ICr53 <- c(24.47262, 17.35234, 34.94743, 13.32203, 20.02948, 11.74731)
ACr <- c(24.13822, 16.53601, 27.61849, 10.0536, 14.45528, 8.185134)

sd(As)
sd(Cd__111)
sd(Cd__114)
sd(Pb)
sd(ICr52)
sd(ICr53)
sd(ACr)

mean(As)
qt(0.95, df=length((As)-1)*sd(As)/(sqrt(length(As))))
mean(Cd__111)
qt(0.95, df=length((Cd__111)-1)*sd(Cd__111)/(sqrt(length(Cd__111))))
mean(Cd__114)
qt(0.95, df=length((Cd__114)-1)*sd(Cd__114)/(sqrt(length(Cd__114))))
mean(Pb)
qt(0.95, df=length((Pb)-1)*sd(Pb)/(sqrt(length(Pb))))
mean(ICr52)
qt(0.95, df=length((ICr52)-1)*sd(ICr52)/(sqrt(length(ICr52))))
mean(ICr53)
qt(0.95, df=length((ICr53)-1)*sd(ICr53)/(sqrt(length(ICr53))))
mean(ACr)
qt(0.95, df=length((ACr)-1)*sd(ACr)/(sqrt(length(ACr))))

```


```{r}

##Percent yield


(2.378705/2.94)*100  #Cd-111
(2.555016/2.94)*100 #Cd-114

(57.83113/121.9)*100 #Cr-52
(59.31501/121.9)*100 #Cr-53
(49.5104/121.9)*100 #Cr (from AA)

(1191.818/150)*100 #Pb208

##Detection and quantification limit

QC_abs <- c(0.0153, 0.0160, 0.0206, 0.0209, 0.0143, 0.0202, 0.0172, 0.0247, 0.0252, 0.0249, 0.0230, 0.0246)
AA_slope_Cr <- 0.013013

LOD <- 3*sd(QC_abs)/AA_slope_Cr
LOQ <- 10*sd(QC_abs)/AA_slope_Cr

LOD
LOQ


```
















