---
title: "chem313_ICPMS_SoilLab"
author: "Emily McLaughlin Sta. Maria"
date: "10/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(readr)
library(janitor)

##For connecting to github, a good habit would be: pulling (down error) when you open r and pushing after you finish a code/finish your rstudio session for the time being

```


```{r}

#importing ICPMS data and sample key 

#warning=FALSE, message=FALSE in {r, ...} will get rid of error messages, if data is too messy there might be a lot of errors

ICPMS_imported <- read.csv("~/chem313/chem313_ICPMS_SoilLab/ICPMS_Data.csv", skip=1, na="N/A")
sample_key <- read.csv("~/chem313/chem313_ICPMS_SoilLab/Sample_Key.csv", skip=0)

View(ICPMS_imported)
sample_key
ICPMS_imported

```

```{r}

#Tidying data

##select part selects RSD columns and renames them with the appropriate metal isotope
## Sample key is also selected for later use in verifying that the RSD data is properly matching the CPS data. 
##then the newly renamed RSD columns are gathered together and a column is created to indicate which metal corresponds to which RSD
##RSD is the error. Idk why I didn't think so haha

RSD_data <- ICPMS_imported %>%
  select(Cr52 = CPS.RSD,
         Cr53 = CPS.RSD.1,
         As75 = CPS.RSD.2,
         Cd111 = CPS.RSD.3,
         Cd114 = CPS.RSD.4,
         Pb208 = CPS.RSD.5,
         Ge_RSD = CPS.RSD.7,
         Sample.Key) %>%
  pivot_longer(1:6,
               names_to = "metal",
               values_to = "RSD")

RSD_data

ICPMS_tidy <- ICPMS_imported %>%
  select(Cr52 = CPS,
         Cr53 = CPS.1,
         As75 = CPS.2,
         Cd111 = CPS.3,
         Cd114 = CPS.4,
         Pb208 = CPS.5,
         Ge72 = CPS.7,
         Sample.Key) %>%
  pivot_longer(1:6,
               names_to = "metal",
               values_to = "CPS") %>%
  mutate(RSD = RSD_data$RSD/RSD_data$Ge_RSD,
         CPS = CPS/Ge72) %>%
  select(-Ge72)
  
##mutate is internal standard correction, it will add a new column, titled RSD. The next part tells you what should be in the column (the math after the equal sign, I think). I think CPS may also be a new column...? 
##select ia ISTD correction. The minus sign gets rid of the Ge72 but keeps all the other columns 


## confirming that RSD data properly matches CPS data. "TRUE" result means everything's good
all(RSD_data$Sample.Key==ICPMS_tidy$Sample.Key, RSD_data$metal==ICPMS_tidy$metal)

ICPMS_tidy

```
```{r}

##merging data

ICPMS_merged <- merge(ICPMS_tidy, sample_key)

ICPMS_merged

```

```{r, warning=FALSE}

##removes clutter from the environment, except for final data set

rm(list=setdiff(ls(), "ICPMS_merged"))

```


```{r}

##exporting data

write.csv(ICPMS_merged, file = "~/chem313/chem313_ICPMS_SoilLab/R/chem313_TidyingICPMS.csv")

```














